//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Moje konto.
        /// </summary>
        public static string aboutMe {
            get {
                return ResourceManager.GetString("aboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chcesz dodać (TAK) czy edytować (NIE) wybrany album?.
        /// </summary>
        public static string AddEditAlbum {
            get {
                return ResourceManager.GetString("AddEditAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chcesz dodać (TAK) czy edytować (NIE) wybranego authora?.
        /// </summary>
        public static string AddEditAuthor {
            get {
                return ResourceManager.GetString("AddEditAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chcesz dodać (TAK) czy edytować (NIE) wybrany utwór?.
        /// </summary>
        public static string AddEditSong {
            get {
                return ResourceManager.GetString("AddEditSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodanie lub edycja albumu.
        /// </summary>
        public static string addOrEditAlbum {
            get {
                return ResourceManager.GetString("addOrEditAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodanie lub edycja autora.
        /// </summary>
        public static string addOrEditAuthor {
            get {
                return ResourceManager.GetString("addOrEditAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodanie lub edycja utworu.
        /// </summary>
        public static string addOrEditSong {
            get {
                return ResourceManager.GetString("addOrEditSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista dostępnych utworów.
        /// </summary>
        public static string albumAvailableSongs {
            get {
                return ResourceManager.GetString("albumAvailableSongs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka albumu.
        /// </summary>
        public static string albumCover {
            get {
                return ResourceManager.GetString("albumCover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka albumu.
        /// </summary>
        public static string albumImage {
            get {
                return ResourceManager.GetString("albumImage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista albumów.
        /// </summary>
        public static string albumList {
            get {
                return ResourceManager.GetString("albumList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista utworów albumu.
        /// </summary>
        public static string albumListSong {
            get {
                return ResourceManager.GetString("albumListSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Albumy.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opcje.
        /// </summary>
        public static string appOptions {
            get {
                return ResourceManager.GetString("appOptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka autora.
        /// </summary>
        public static string authorCover {
            get {
                return ResourceManager.GetString("authorCover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka autora.
        /// </summary>
        public static string authorImage {
            get {
                return ResourceManager.GetString("authorImage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa autora.
        /// </summary>
        public static string authorName {
            get {
                return ResourceManager.GetString("authorName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak autora o podanym ID/nazwie.
        /// </summary>
        public static string authorNotExistDB {
            get {
                return ResourceManager.GetString("authorNotExistDB", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twórcy.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kup ten album.
        /// </summary>
        public static string buyAlbum {
            get {
                return ResourceManager.GetString("buyAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kup ten album (test).
        /// </summary>
        public static string buyAlbumTest {
            get {
                return ResourceManager.GetString("buyAlbumTest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kup ten utwór.
        /// </summary>
        public static string buySong {
            get {
                return ResourceManager.GetString("buySong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kup ten utwór (test).
        /// </summary>
        public static string buySongTest {
            get {
                return ResourceManager.GetString("buySongTest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj to zamówienie.
        /// </summary>
        public static string cancelThisOrder {
            get {
                return ResourceManager.GetString("cancelThisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło.
        /// </summary>
        public static string changePass {
            get {
                return ResourceManager.GetString("changePass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień motyw.
        /// </summary>
        public static string changetheme {
            get {
                return ResourceManager.GetString("changetheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID wybranego albumu.
        /// </summary>
        public static string choosenAlbumID {
            get {
                return ResourceManager.GetString("choosenAlbumID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID wybranych utworów.
        /// </summary>
        public static string choosenAlbumSongsID {
            get {
                return ResourceManager.GetString("choosenAlbumSongsID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID wybranego autora.
        /// </summary>
        public static string choosenAuthorID {
            get {
                return ResourceManager.GetString("choosenAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID wybranego zamówienia.
        /// </summary>
        public static string choosenOrderID {
            get {
                return ResourceManager.GetString("choosenOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID wybranego utworu.
        /// </summary>
        public static string choosenSongID {
            get {
                return ResourceManager.GetString("choosenSongID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz zdjęcie.
        /// </summary>
        public static string choosephoto {
            get {
                return ResourceManager.GetString("choosephoto", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uzupełnij pola!.
        /// </summary>
        public static string completeFields {
            get {
                return ResourceManager.GetString("completeFields", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uzupełnij dane logowania!.
        /// </summary>
        public static string completeLoginPass {
            get {
                return ResourceManager.GetString("completeLoginPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka zamówionego produktu.
        /// </summary>
        public static string coverOfOrderedProduct {
            get {
                return ResourceManager.GetString("coverOfOrderedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka zamówionego produktu.
        /// </summary>
        public static string coverOrderedProduct {
            get {
                return ResourceManager.GetString("coverOrderedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rabat.
        /// </summary>
        public static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyłącz program.
        /// </summary>
        public static string exitApp {
            get {
                return ResourceManager.GetString("exitApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lokalizacja.
        /// </summary>
        public static string localizationApp {
            get {
                return ResourceManager.GetString("localizationApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zalogowano.
        /// </summary>
        public static string loggedIn {
            get {
                return ResourceManager.GetString("loggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyloguj.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Moje zamówienia.
        /// </summary>
        public static string myOrders {
            get {
                return ResourceManager.GetString("myOrders", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa pliku okładki autora.
        /// </summary>
        public static string nameImageAuthor {
            get {
                return ResourceManager.GetString("nameImageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa okładki utworu.
        /// </summary>
        public static string nameImageSong {
            get {
                return ResourceManager.GetString("nameImageSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa albumu.
        /// </summary>
        public static string nameOfAlbum {
            get {
                return ResourceManager.GetString("nameOfAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa pliku okładki albumu.
        /// </summary>
        public static string nameOfImageAlbum {
            get {
                return ResourceManager.GetString("nameOfImageAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa studia.
        /// </summary>
        public static string nameofstudio {
            get {
                return ResourceManager.GetString("nameofstudio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowe hasło.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie wszystkie pola zostały wypełnione!.
        /// </summary>
        public static string notAllFieldsFillUp {
            get {
                return ResourceManager.GetString("notAllFieldsFillUp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasła nie są zgodne!.
        /// </summary>
        public static string notCompPass {
            get {
                return ResourceManager.GetString("notCompPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak wystarczającej gotówki..
        /// </summary>
        public static string notenoughcash {
            get {
                return ResourceManager.GetString("notenoughcash", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stare hasło.
        /// </summary>
        public static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zatwierdź zamówienie.
        /// </summary>
        public static string orderConfirm {
            get {
                return ResourceManager.GetString("orderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Koszt zamówienia.
        /// </summary>
        public static string orderCost {
            get {
                return ResourceManager.GetString("orderCost", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamówiony produkt.
        /// </summary>
        public static string orderProduct {
            get {
                return ResourceManager.GetString("orderProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamówienia.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dane adresowe użytkownika.
        /// </summary>
        public static string orderUserAddress {
            get {
                return ResourceManager.GetString("orderUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID Usera z zamówienia.
        /// </summary>
        public static string orderUserID {
            get {
                return ResourceManager.GetString("orderUserID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię i nazwisko użytkownika.
        /// </summary>
        public static string orderUserNameSurname {
            get {
                return ResourceManager.GetString("orderUserNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ścieżka okładki albumu.
        /// </summary>
        public static string pathImageAlbum {
            get {
                return ResourceManager.GetString("pathImageAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ścieżka okładki autora.
        /// </summary>
        public static string pathImageAuthor {
            get {
                return ResourceManager.GetString("pathImageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ścieżka okładki utworu.
        /// </summary>
        public static string pathImageSong {
            get {
                return ResourceManager.GetString("pathImageSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cena albumu.
        /// </summary>
        public static string priceOfAlbum {
            get {
                return ResourceManager.GetString("priceOfAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cena utworu.
        /// </summary>
        public static string priceOfSong {
            get {
                return ResourceManager.GetString("priceOfSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klucz produktu.
        /// </summary>
        public static string productkey {
            get {
                return ResourceManager.GetString("productkey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia programu.
        /// </summary>
        public static string programSettings {
            get {
                return ResourceManager.GetString("programSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powtórz nowe hasło.
        /// </summary>
        public static string RepeatNewPass {
            get {
                return ResourceManager.GetString("RepeatNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz autora.
        /// </summary>
        public static string selectAuthor {
            get {
                return ResourceManager.GetString("selectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybrane ID.
        /// </summary>
        public static string selectedID {
            get {
                return ResourceManager.GetString("selectedID", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj się.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka utworu.
        /// </summary>
        public static string songCover {
            get {
                return ResourceManager.GetString("songCover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka utworu.
        /// </summary>
        public static string songImage {
            get {
                return ResourceManager.GetString("songImage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa utworu.
        /// </summary>
        public static string songName {
            get {
                return ResourceManager.GetString("songName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwory.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okładka studia.
        /// </summary>
        public static string studiocover {
            get {
                return ResourceManager.GetString("studiocover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy jesteś pewien, że to poprawne zdjęcie okładki albumu?.
        /// </summary>
        public static string sureAlbum {
            get {
                return ResourceManager.GetString("sureAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy jesteś pewien, że to poprawne zdjęcie okładki autora?.
        /// </summary>
        public static string sureAuthor {
            get {
                return ResourceManager.GetString("sureAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy jesteś pewien, że to poprawne zdjęcie okładki utworu?.
        /// </summary>
        public static string sureSong {
            get {
                return ResourceManager.GetString("sureSong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Regulamin.
        /// </summary>
        public static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres.
        /// </summary>
        public static string UserAddress {
            get {
                return ResourceManager.GetString("UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Admin.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gotówka.
        /// </summary>
        public static string UserCash {
            get {
                return ResourceManager.GetString("UserCash", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miasto.
        /// </summary>
        public static string UserCity {
            get {
                return ResourceManager.GetString("UserCity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownik nie istnieje!.
        /// </summary>
        public static string userDoesntExist {
            get {
                return ResourceManager.GetString("userDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownik istnieje!.
        /// </summary>
        public static string userexists {
            get {
                return ResourceManager.GetString("userexists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika istnieje!.
        /// </summary>
        public static string userNameExists {
            get {
                return ResourceManager.GetString("userNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestrowano.
        /// </summary>
        public static string userRegistered {
            get {
                return ResourceManager.GetString("userRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użytkownicy.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwisko.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        public static string UserUserName {
            get {
                return ResourceManager.GetString("UserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz adres.
        /// </summary>
        public static string writeaddress {
            get {
                return ResourceManager.GetString("writeaddress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz miasto.
        /// </summary>
        public static string writecity {
            get {
                return ResourceManager.GetString("writecity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz login.
        /// </summary>
        public static string writelogin {
            get {
                return ResourceManager.GetString("writelogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj imię.
        /// </summary>
        public static string writename {
            get {
                return ResourceManager.GetString("writename", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz hasło.
        /// </summary>
        public static string writepass {
            get {
                return ResourceManager.GetString("writepass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz hasło.
        /// </summary>
        public static string writepassword {
            get {
                return ResourceManager.GetString("writepassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powtórz hasło.
        /// </summary>
        public static string writepasswordagain {
            get {
                return ResourceManager.GetString("writepasswordagain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj nazwisko.
        /// </summary>
        public static string writesurname {
            get {
                return ResourceManager.GetString("writesurname", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj nazwę użytkownika.
        /// </summary>
        public static string writeusername {
            get {
                return ResourceManager.GetString("writeusername", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Złe hasło!.
        /// </summary>
        public static string wrongPass {
            get {
                return ResourceManager.GetString("wrongPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie możesz kupić tego produktu - nie posiadasz tyle gotówki..
        /// </summary>
        public static string youcantbuymoney {
            get {
                return ResourceManager.GetString("youcantbuymoney", resourceCulture);
            }
        }
    }
}
